name = "An Awesome Adventure - Ode to Leonor"
author = "PrKiyo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83787cd66252b2499072894ead881b70f5502d4b21d03fc0053b5069149bb44d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
