name = "An Awesome Adventure - Ode to Leonor"
author = "PrKiyo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db7bea5d8edd5a61b5bf7efd5c21e589cea96959b47f115b36810e08f61b89f0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
datapack-folder = "datapacks"
