name = "An Awesome Adventure - Ode to Leonor"
author = "PrKiyo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1a25a84befd803033bbb9771b78f3abe4ccbeaf7c60e821f781da77d0057e7e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
