param(
    [string]$SeedFile = "config/worldgen/seed-candidates.csv",
    [string]$ServerDir = "../tools/server",
    [switch]$BootServerSmokeTest,
    [int]$StartupTimeoutSeconds = 120,
    [switch]$SkipModSync,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$seedFilePath = Join-Path $repoRoot $SeedFile
$serverDirPath = Resolve-Path (Join-Path $repoRoot $ServerDir) -ErrorAction Stop
$serverPropertiesPath = Join-Path $serverDirPath "server.properties"
$runPregenPath = Join-Path $serverDirPath "run-pregen.ps1"

if (-not (Test-Path $seedFilePath)) {
    throw "Seed file not found: $seedFilePath"
}
if (-not (Test-Path $runPregenPath)) {
    throw "run-pregen.ps1 not found: $runPregenPath"
}

$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$reportPath = Join-Path $repoRoot "reports/seed-eval-$timestamp.csv"
$rows = Import-Csv -Path $seedFilePath
if (-not $rows -or $rows.Count -eq 0) {
    throw "No seed candidates found in $seedFilePath"
}

function Set-LevelSeed {
    param(
        [string]$FilePath,
        [string]$Seed
    )

    if (-not (Test-Path $FilePath)) {
        Set-Content -Path $FilePath -Value @(
            "# Generated by scripts/evaluate-seeds.ps1",
            "level-seed=$Seed"
        )
        return
    }

    $content = Get-Content -Path $FilePath
    $found = $false
    for ($i = 0; $i -lt $content.Count; $i++) {
        if ($content[$i] -match '^level-seed=') {
            $content[$i] = "level-seed=$Seed"
            $found = $true
            break
        }
    }

    if (-not $found) {
        $content += "level-seed=$Seed"
    }

    Set-Content -Path $FilePath -Value $content
}

function Test-BootMarker {
    param(
        [string]$LogPath,
        [DateTime]$Since,
        [int]$TimeoutSeconds
    )

    $marker = "Done ("
    $stopwatch = [System.Diagnostics.Stopwatch]::StartNew()

    while ($stopwatch.Elapsed.TotalSeconds -lt $TimeoutSeconds) {
        if (Test-Path $LogPath) {
            $lines = Get-Content -Path $LogPath -Tail 200 -ErrorAction SilentlyContinue
            foreach ($line in $lines) {
                if ($line -like "*$marker*") {
                    return @{ Found = $true; Seconds = [math]::Round($stopwatch.Elapsed.TotalSeconds, 2) }
                }
            }
        }
        Start-Sleep -Seconds 2
    }

    return @{ Found = $false; Seconds = [math]::Round($stopwatch.Elapsed.TotalSeconds, 2) }
}

function Invoke-ServerSmokeTest {
    param(
        [string]$WorkingDir,
        [int]$TimeoutSeconds
    )

    $runBat = Join-Path $WorkingDir "run.bat"
    $latestLog = Join-Path $WorkingDir "logs/latest.log"
    if (-not (Test-Path $runBat)) {
        throw "run.bat not found: $runBat"
    }

    $process = Start-Process -FilePath "cmd.exe" -ArgumentList "/c", "run.bat nogui" -WorkingDirectory $WorkingDir -PassThru
    try {
        $result = Test-BootMarker -LogPath $latestLog -Since (Get-Date) -TimeoutSeconds $TimeoutSeconds
        return $result
    }
    finally {
        if (-not $process.HasExited) {
            Stop-Process -Id $process.Id -Force
        }
    }
}

$reportRecords = @()
$first = $true

foreach ($row in $rows) {
    $seed = [string]$row.seed
    $slug = [string]$row.slug
    $source = [string]$row.source
    $status = [string]$row.status

    if ([string]::IsNullOrWhiteSpace($seed)) {
        continue
    }

    Write-Host "Evaluating seed=$seed slug=$slug" -ForegroundColor Cyan

    $bootSuccess = $false
    $startupSeconds = ""
    $logMarkerFound = $false
    $reportNotes = ""

    if ($DryRun) {
        $reportNotes = "dry-run"
    }
    else {
        Set-LevelSeed -FilePath $serverPropertiesPath -Seed $seed

        $pregenArgs = @()
        if (-not $first -or $SkipModSync) {
            $pregenArgs += "-SkipModSync"
        }
        $pregenArgs += "-NoLaunch"

        & $runPregenPath @pregenArgs

        if ($BootServerSmokeTest) {
            $smoke = Invoke-ServerSmokeTest -WorkingDir $serverDirPath -TimeoutSeconds $StartupTimeoutSeconds
            $bootSuccess = [bool]$smoke.Found
            $startupSeconds = [string]$smoke.Seconds
            $logMarkerFound = [bool]$smoke.Found
            if (-not $smoke.Found) {
                $reportNotes = "boot marker timeout"
            }
        }
        else {
            $reportNotes = "prepared-no-boot"
        }
    }

    $record = [PSCustomObject]@{
        timestamp = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss")
        seed = $seed
        slug = $slug
        source = $source
        status = $status
        bootSuccess = $bootSuccess
        startupSeconds = $startupSeconds
        logMarkerFound = $logMarkerFound
        reportNotes = $reportNotes
    }

    $reportRecords += $record
    $first = $false
}

$reportRecords | Export-Csv -Path $reportPath -NoTypeInformation
Write-Host "Report written: $reportPath" -ForegroundColor Green
